name: laravel_echo
description: Port of official Laravel Echo package for your Flutter apps.
version: 0.2.1
author: Kakajan SH <mervasdayi@gmail.com>
homepage: https://github.com/kakajansh/echo

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pusher_websocket_flutter: ^0.2.0
  socket_io_client: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
